# Generated by Django 2.2.6 on 2019-10-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='cinema.Performs', to='cinema.Artist'),
        ),
    ]
